Clients:
    - Hostname: Kin3D-1
      Ip:       192.168.4.176
      Port:     8881
      
    - Hostname: kin3d-2
      Ip:       192.168.4.175
      Port:     8881
      
#    - Hostname: kin3d-3
#      Ip:       192.168.4.174
#      Port:     8881
      
Server:
    Ip:           192.168.4.174
    Port:         8882
    WithFrontend: false
    CameraCalibrations:
        - Hostname: Kin3D-1
          Path: /home/killavus/calib_kin1_1704
        - Hostname: kin3d-2
          Path: /home/killavus/calib_kin2_1704
        - Hostname: kin3d-3
          Path: /home/killavus/calib_kin3_1704

MaxDistBetweenFramesInBatch: 45
MinNumberOfFramesInPackageToAccept: 2
OutputDirectory: output

#Mode: SEND_ALL -> 0
#      SEND_DEPTH -> 1
Mode: 1
MaxNumFramesToBeSent: 800
