Clients:
#    - Hostname: Kin3D-1
#      Ip:       127.0.0.1
#      Port:     8101
      
#    - Hostname: kin3d-2
#      Ip:       192.168.4.175
#      Port:     8881
      
    - Hostname: kin3d-3
      Ip:       192.168.4.174
      Port:     8001
      
Server:
    Ip:           127.0.0.1 
    Port:         8002
    WithFrontend: true
    CameraCalibrations:
        - Hostname: kin3d-3
          Path: /home/kin3d-3/Documents/D3DH-Client/build/calib_kin3_1704

MaxDistBetweenFramesInBatch: 45
MinNumberOfFramesInPackageToAccept: 1
OutputDirectory: output

#Mode: SEND_ALL -> 0
#      SEND_DEPTH -> 1
Mode: 1
MaxNumFramesToBeSent: 800
